In [ ]:
import pandas as pd
import numpy as np
import os

In [13]:
# 1. CSV 파일 불러오기
df = pd.read_csv('delisted_financials_all.csv')

In [14]:
# 2. statement_name이 '현금흐름표'인 행 제외
df = df[df['statement_name'] != '현금흐름표']

# 3. account_num 칼럼 삭제
if 'account_num' in df.columns:
    df = df.drop(columns=['account_num'])

# 4. ticker로 그룹화, account_id를 column으로 pivot
pivot_df = df.pivot_table(
    index='ticker',
    columns='account_id',
    values='this_term_amount',  # 실제 값 컬럼명으로 변경
    aggfunc='first'  # 여러 값이 있으면 첫 번째 값 사용
)

# 결과 확인
print(pivot_df.head())

account_id  -표준계정코드 미사용-  dart_AccumulatedDepreciationBuildingsGross  \
ticker
4740                 NaN                                         NaN
5450        0.000000e+00                                         NaN
5980       -1.369019e+09                                         NaN
6580        5.947411e+08                                         NaN
7630       -5.959628e+08                                         NaN

account_id  dart_AccumulatedDepreciationConstructionInProgressGross  \
ticker
4740                                                      NaN
5450                                                      NaN
5980                                                      NaN
6580                                                      NaN
7630                                                      NaN

account_id  dart_AccumulatedDepreciationFinanceLeaseAssetGross  \
ticker
4740                                                      NaN
5450                                                      NaN
5980                                                      NaN
6580                                                      NaN
7630                                                      NaN

account_id  dart_AccumulatedDepreciationFittingGross  \
ticker
4740                                             NaN
5450                                             NaN
5980                                             NaN
6580                                             NaN
7630                                             NaN

account_id  dart_AccumulatedDepreciationInvestmentProperty  \
ticker
4740                                                   NaN
5450                                                   NaN
5980                                                   NaN
6580                                                   NaN
7630                                                   NaN

account_id  dart_AccumulatedDepreciationMachineryGross  \
ticker
4740                                               NaN
5450                                               NaN
5980                                               NaN
6580                                               NaN
7630                                               NaN

account_id  dart_AccumulatedDepreciationOfficeEquipmentGross  \
ticker
4740                                                     NaN
5450                                                     NaN
5980                                                     NaN
6580                                                     NaN
7630                                                     NaN

account_id  dart_AccumulatedDepreciationOtherPropertyPlantAndEquipmentGross  \
ticker
4740                                                      NaN
5450                                                      NaN
5980                                                      NaN
6580                                                      NaN
7630                                                      NaN

account_id  dart_AccumulatedDepreciationShipsGross  ...  \
ticker                                              ...
4740                                           NaN  ...
5450                                           NaN  ...
5980                                           NaN  ...
6580                                           NaN  ...
7630                                           NaN  ...

account_id  ifrs_ShareOfProfitLossOfAssociatesAndJointVenturesAccountedForUsingEquityMethod  \
ticker
4740                                                      NaN
5450                                                      NaN
5980                                                      NaN
6580                                                      NaN
7630                                                      NaN

account_id  ifrs_SharePremium  ifrs_SharebasedPaymentTransactions  \
ticker
4740                      NaN                                 NaN
5450                      NaN                                 NaN
5980                      NaN                                 NaN
6580                      NaN                                 NaN
7630                      NaN                                 NaN

account_id  ifrs_ShorttermBorrowings  \
ticker
4740                             NaN
5450                             NaN
5980                    1.955924e+10
6580                             NaN
7630                             NaN

account_id  ifrs_ShorttermInvestmentsClassifiedAsCashEquivalents  \
ticker
4740                                                      NaN
5450                                                      NaN
5980                                                      NaN
6580                                                      NaN
7630                                                      NaN

account_id  ifrs_ShorttermMiscellaneousOtherProvisions  \
ticker
4740                                               NaN
5450                                               NaN
5980                                               NaN
6580                                               NaN
7630                                               NaN

account_id  ifrs_ShorttermOnerousContractsProvision  \
ticker
4740                                            NaN
5450                                            NaN
5980                                            NaN
6580                                            NaN
7630                                            NaN

account_id  ifrs_TradeAndOtherCurrentPayables  \
ticker
4740                             3.285144e+09
5450                                      NaN
5980                             2.144104e+10
6580                                      NaN
7630                                      NaN

account_id  ifrs_TradeAndOtherCurrentReceivables  ifrs_TreasuryShares
ticker
4740                                2.994399e+09                  NaN
5450                                         NaN                  NaN
5980                                2.389419e+10                  NaN
6580                                         NaN                  NaN
7630                                         NaN                  NaN

[5 rows x 598 columns]

In [11]:
df.columns

Index(['ticker', 'year', 'account_id', 'account_nm', 'account_detail',
       'this_term_amount', 'prev_term_amount', 'statement_name', 'fs_div'],
      dtype='object')

In [15]:
pivot_df.head()

account_id,-표준계정코드 미사용-,dart_AccumulatedDepreciationBuildingsGross,dart_AccumulatedDepreciationConstructionInProgressGross,dart_AccumulatedDepreciationFinanceLeaseAssetGross,dart_AccumulatedDepreciationFittingGross,dart_AccumulatedDepreciationInvestmentProperty,dart_AccumulatedDepreciationMachineryGross,dart_AccumulatedDepreciationOfficeEquipmentGross,dart_AccumulatedDepreciationOtherPropertyPlantAndEquipmentGross,dart_AccumulatedDepreciationShipsGross,...,ifrs_ShareOfProfitLossOfAssociatesAndJointVenturesAccountedForUsingEquityMethod,ifrs_SharePremium,ifrs_SharebasedPaymentTransactions,ifrs_ShorttermBorrowings,ifrs_ShorttermInvestmentsClassifiedAsCashEquivalents,ifrs_ShorttermMiscellaneousOtherProvisions,ifrs_ShorttermOnerousContractsProvision,ifrs_TradeAndOtherCurrentPayables,ifrs_TradeAndOtherCurrentReceivables,ifrs_TreasuryShares
ticker,,,,,,,,,,,,,,,,,,,,,
4740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.285144e+09,2.994399e+09,NaN
5450,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5980,-1.369019e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.955924e+10,NaN,NaN,NaN,2.144104e+10,2.389419e+10,NaN
6580,5.947411e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7630,-5.959628e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
pivot_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115 entries, 4740 to 950180
Columns: 598 entries, -표준계정코드 미사용- to ifrs_TreasuryShares
dtypes: float64(598)
memory usage: 538.2 KB

In [ ]:
pivot_df

account_id,-표준계정코드 미사용-,dart_AccumulatedDepreciationBuildingsGross,dart_AccumulatedDepreciationConstructionInProgressGross,dart_AccumulatedDepreciationFinanceLeaseAssetGross,dart_AccumulatedDepreciationFittingGross,dart_AccumulatedDepreciationInvestmentProperty,dart_AccumulatedDepreciationMachineryGross,dart_AccumulatedDepreciationOfficeEquipmentGross,dart_AccumulatedDepreciationOtherPropertyPlantAndEquipmentGross,dart_AccumulatedDepreciationShipsGross,...,ifrs_ShareOfProfitLossOfAssociatesAndJointVenturesAccountedForUsingEquityMethod,ifrs_SharePremium,ifrs_SharebasedPaymentTransactions,ifrs_ShorttermBorrowings,ifrs_ShorttermInvestmentsClassifiedAsCashEquivalents,ifrs_ShorttermMiscellaneousOtherProvisions,ifrs_ShorttermOnerousContractsProvision,ifrs_TradeAndOtherCurrentPayables,ifrs_TradeAndOtherCurrentReceivables,ifrs_TreasuryShares
count,1.080000e+02,5.000000e+00,1.0,1.000000e+00,1.000000e+00,1.0,6.000000e+00,4.000000e+00,5.000000e+00,2.0,...,2.000000e+00,7.000000e+00,1.0,1.400000e+01,1.0,2.000000e+00,1.0,2.600000e+01,2.500000e+01,3.000000e+00
mean,3.844953e+09,1.292463e+10,676305290.0,2.620100e+09,1.346404e+09,0.0,3.720084e+10,2.612814e+09,1.284992e+09,0.0,...,-9.475000e+05,4.207905e+10,0.0,1.697705e+10,0.0,5.000000e+06,19867500.0,1.830855e+10,1.795899e+10,7.033854e+07
std,1.317991e+10,1.944152e+10,NaN,NaN,NaN,NaN,5.284344e+10,1.833565e+09,8.627427e+08,0.0,...,1.339967e+06,3.565623e+10,NaN,2.807050e+10,NaN,7.071068e+06,NaN,3.113880e+10,2.842648e+10,6.113431e+07
min,-2.711916e+10,7.558513e+08,676305290.0,2.620100e+09,1.346404e+09,0.0,0.000000e+00,6.988500e+07,2.219938e+08,0.0,...,-1.895000e+06,6.019718e+09,0.0,0.000000e+00,0.0,0.000000e+00,19867500.0,4.011866e+07,3.327589e+07,0.000000e+00
25%,0.000000e+00,2.496810e+09,676305290.0,2.620100e+09,1.346404e+09,0.0,4.471576e+09,2.048980e+09,6.757889e+08,0.0,...,-1.421250e+06,1.929080e+10,0.0,1.880292e+09,0.0,2.500000e+06,19867500.0,1.938683e+09,1.754698e+09,5.016686e+07
50%,2.204203e+08,6.494740e+09,676305290.0,2.620100e+09,1.346404e+09,0.0,2.342591e+10,2.994991e+09,1.332152e+09,0.0,...,-9.475000e+05,3.324668e+10,0.0,8.433296e+09,0.0,5.000000e+06,19867500.0,6.091876e+09,7.562425e+09,1.003337e+08
75%,2.306075e+09,7.532349e+09,676305290.0,2.620100e+09,1.346404e+09,0.0,3.388308e+10,3.558826e+09,1.820380e+09,0.0,...,-4.737500e+05,5.225374e+10,0.0,1.884591e+10,0.0,7.500000e+06,19867500.0,2.133991e+10,1.984794e+10,1.055078e+08
max,8.520066e+10,4.734341e+10,676305290.0,2.620100e+09,1.346404e+09,0.0,1.408310e+11,4.391388e+09,2.374644e+09,0.0,...,0.000000e+00,1.121979e+11,0.0,1.092833e+11,0.0,1.000000e+07,19867500.0,1.365618e+11,1.162928e+11,1.106819e+08

In [ ]:
print(pivot_df.isna().sum())

account_id
-표준계정코드 미사용-                                                 7
dart_AccumulatedDepreciationBuildingsGross                 110
dart_AccumulatedDepreciationConstructionInProgressGross    114
dart_AccumulatedDepreciationFinanceLeaseAssetGross         114
dart_AccumulatedDepreciationFittingGross                   114
                                                          ...
ifrs_ShorttermMiscellaneousOtherProvisions                 113
ifrs_ShorttermOnerousContractsProvision                    114
ifrs_TradeAndOtherCurrentPayables                           89
ifrs_TradeAndOtherCurrentReceivables                        90
ifrs_TreasuryShares                                        112
Length: 598, dtype: int64

In [22]:
pivot_df.isna().sum().to_csv('pivot_nan_count.csv')

In [26]:
pivot_df['ifrs_SharebasedPaymentTransactions'].isnull

<bound method Series.isnull of ticker
4740     NaN
5450     NaN
5980     NaN
6580     NaN
7630     NaN
          ..
354230   NaN
900050   NaN
900130   NaN
900180   NaN
950180   NaN
Name: ifrs_SharebasedPaymentTransactions, Length: 115, dtype: float64>

In [27]:
pivot_df = pivot_df.drop(columns=['ifrs_Cash', 'ifrs_CashOnHand', 'ifrs_BalancesWithBanks', 'ifrs_CashEquivalents', 'ifrs_ShorttermInvestmentsClassifiedAsCashEquivalents'])

In [28]:
# 분자: ifrs-full_Assets 또는 ifrs_Assets
assets = None
if 'ifrs-full_Assets' in pivot_df.columns:
    assets = pivot_df['ifrs-full_Assets']
elif 'ifrs_Assets' in pivot_df.columns:
    assets = pivot_df['ifrs_Assets']
else:
    print('자산 계정이 없습니다.')

# 분모: ifrs-full_CurrentLiabilities 또는 ifrs_CurrentLiabilities
current_liabilities = None
if 'ifrs-full_CurrentLiabilities' in pivot_df.columns:
    current_liabilities = pivot_df['ifrs-full_CurrentLiabilities']
elif 'ifrs_CurrentLiabilities' in pivot_df.columns:
    current_liabilities = pivot_df['ifrs_CurrentLiabilities']
else:
    print('유동부채 계정이 없습니다.')

# current_ratio 계산 및 컬럼 추가
if (assets is not None) and (current_liabilities is not None):
    pivot_df['current_ratio'] = assets / current_liabilities
else:
    pivot_df['current_ratio'] = np.nan  # 둘 다 없으면 NaN

# 결과 확인
print(pivot_df[['current_ratio']].head())

account_id  current_ratio
ticker
4740                  NaN
5450             1.484117
5980                  NaN
6580             3.736533
7630             1.814849